return {
    -- {
    --     "benlubas/molten-nvim",
    --     -- version = "^1.0.0", -- use version <2.0.0 to avoid breaking changes
    --     dependencies = { "3rd/image.nvim" },
    --     build = ":UpdateRemotePlugins",
    --     init = function()
    --         -- these are examples, not defaults. Please see the readme
    --         vim.g.molten_image_provider = "image.nvim"
    --         vim.g.molten_output_win_max_height = 20
    --         vim.g.molten_wrap_output = true
    --         vim.g.molten_virt_text_output = true
    --         vim.g.molten_virt_lines_off_by_1 = true
    --
    --         vim.g.python3_host_prog = vim.fn.expand "~/Desktop/.molten-venv/bin/python3"
    --     end,
    --     keys = {
    --         { "<leader>je", "<cmd>MoltenEvaluateOperator<cr>", desc = "Evaluate operator" },
    --         { "<leader>jo", "<cmd>noautocmd MoltenEnterOutput<cr>", desc = "Open output window" },
    --         { "<leader>jh", "<cmd>MoltenHideOutput<cr>", desc = "Hide output" },
    --         { "<leader>jd", "<cmd>MoltenDelete<cr>", desc = "Delete cell" },
    --         { "<leader>jb", "<cmd>MoltenOpenInBrowser<cr>", desc = "Open in browser" },
    --     },
    -- },
    --
    -- -- {
    -- --     "quarto-dev/quarto-nvim",
    -- --     dependencies = {
    -- --         "jmbuhr/otter.nvim",
    -- --         "nvim-treesitter/nvim-treesitter",
    -- --     },
    -- -- },
    --
    -- {
    --     "3rd/image.nvim",
    --     opts = {
    --         backend = "sixel", -- whatever backend you would like to use
    --         max_width = 100,
    --         max_height = 12,
    --         max_height_window_percentage = math.huge,
    --         max_width_window_percentage = math.huge,
    --         window_overlap_clear_enabled = true, -- toggles images when windows are overlapped
    --         window_overlap_clear_ft_ignore = { "cmp_menu", "cmp_docs", "" },
    --     },
    -- },
}
